version: "3.7"
services:


  policy-api:
    image: orchestracities/anubis-management-api:edge
    networks:
      - envoymesh
    ports:
      - "8085:8000"

  keycloak:
    image: jboss/keycloak:${KEYCLOAK_VERSION:-16.1.1}
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/oc-custom.jar:/opt/jboss/keycloak/standalone/deployments/oc-custom.jar
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
    networks:
      - envoymesh

volumes:
  mongodata:

networks:
  envoymesh: {}
